### ISSUE TITLE
Where can I download the trained model parameters?

### ISSUE THREAD

**Issue by tinyxuyan** [nadavbh12/Character-Level-Language-Modeling-with-Deeper-Self-Attention-pytorch#1]
I want to do some work with the trained NN of character-level language model. Your work is a good example. However, I can not find the trained model in public, such as Huggingface Transformer. Could you please give me some advice?

**Comment by nadavbh12** [comment]
I'm afraid I didn't save any of the models I trained with repository (it's been over 3 years now).
The package has training code. So training one yourslef shouldn't be a problem.
I'm sure you can also find other repositories with newer algorithms with pre-trained models.
