### ISSUE TITLE
vocab_size for char embed?

### ISSUE THREAD

**Issue by shouldsee** [nadavbh12/Character-Level-Language-Modeling-with-Deeper-Self-Attention-pytorch#2]
Hi thanks for sharing.

From the paper, it seems they are doing a character level embedding. but from running main.py, i got a word level model instead? Not sure whether this is consistent with the paper specification?

```python
209  	        model.zero_grad()
210  ->	        output = model(data, target_mask)
211  	        loss, last_loss = model.criterion(output, target)
```

```python
data.max()
# tensor(32647, device='cuda:0')
model.vocab_size
# 33278
```

**Comment by nadavbh12** [comment]
I am no longer developing this repository. If you get consistent results with character level, feel free to send pull request
